version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-server
  web:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: app-server
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
    ports:
      - 5000:5000
